// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.InteropServices;

namespace WebApplication2.Models;

public partial class Account
{
    public int Id { get; set; }
    [DisplayName("Tài khoản")]
    [Required (ErrorMessage = "Bạn hãy nhập tài khoản đăng nhập")]
    public string UserName { get; set; }
    [Required(ErrorMessage = "Bạn hãy nhập mật khẩu đăng nhập")]
    [DisplayName("Mật khẩu")]
    [DataType(DataType.Password)]
    public string Password { get; set; }
    public string Admin { get; set; }
    [DisplayName("Họ")]
    public string FirstName { get; set; }
    [DisplayName("Tên")]
    public string LastName { get; set; }
}