// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication2.Models;

public partial class Product
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Alias { get; set; }

    public int? CategoryId { get; set; }

    public string Images { get; set; }

    public DateTime? CreatedDate { get; set; }

    public decimal? Price { get; set; }

    public string Detail { get; set; }

    public bool? Status { get; set; }
}