// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication2.Models;

public partial class Account
{
    public int Id { get; set; }

    public string UserName { get; set; }

    public string Password { get; set; }

    public string Admin { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }
}