// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace WebApplication2.Models;

public partial class Category
{
	[StringLength(50, ErrorMessage = "Số ký tự tối đa là 50")]
    [DisplayName("Tên danh mục")]
	[Required(ErrorMessage = "Bạn chưa nhập tên danh mục")]
    public string Name { get; set; }
    [DisplayName("Tiêu đề SEO")]
    public string Alias { get; set; }
	[DisplayName("Danh mục cha")]
	public int? ParentId { get; set; }
	[DisplayName("Ngày tạo")]
	public DateTime? CreatedDate { get; set; }
	[DisplayName("Thứ tự")]
	[Range(0, Int32.MaxValue, ErrorMessage = "Bạn phải nhập số")]
	public int? Order { get; set; }
	[DisplayName("Trạng thái")]
	public bool? Status { get; set; }

    public int Id { get; set; }
}