// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication2.Models;

public partial class Credential
{
    public string UserGroupId { get; set; }

    public string RoleId { get; set; }
}