// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication2.Models;

public partial class Footer
{
    public string Id { get; set; }

    public string Content { get; set; }

    public bool? Status { get; set; }
}