// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication2.Models;

public partial class ProductCategory
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string MetaTitle { get; set; }

    public int? ParentId { get; set; }

    public int? DisplayOrder { get; set; }

    public string SeoTitle { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string ModifiedBy { get; set; }

    public string MetaKeywords { get; set; }

    public string MetaDescriptions { get; set; }

    public bool Status { get; set; }

    public string ShowOnHome { get; set; }
}