// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication2.Models;

public partial class Silde
{
    public int Id { get; set; }

    public string Image { get; set; }

    public int? DispalyOrder { get; set; }

    public string Link { get; set; }

    public string Description { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public string ModifiedBy { get; set; }

    public bool? Status { get; set; }
}